<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-S43CKGL" ignored="0" name="Me" tests="2" failures="1" timestamp="28 Sep 2018 08:33:07 GMT" time="12.776" errors="0">
  <testcase name="run" time="0.796" classname="script.TestRun">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestRun.run(TestRun.java:19)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.133" classname="script.TestRun2"/>
</testsuite> <!-- Me -->
